In [4]:
import pandas as pd
%matplotlib inline

In [6]:
tweet=pd.read_csv('badbot.csv')
tweet.head()

,id,tweet_id,created_at,retweet_count,favorite_count,text,name,screen_name,bot_type,#of_followers,#of_friends,status_num,url,lang,time_zone,location,default_profile,default_profile_image,geo_enabled,profile_image_url
0,214549887,1191290000000000000,11/4/2019 9:27,0,0,b'@walletofsatoshi @ChipiChipiBmbn @fabthefoxx...,Karliatto,karliatto,1,48,161,21,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...
1,214549887,1186270000000000000,10/21/2019 13:27,4,18,b'Still digesting the experience at @LNconf #T...,Karliatto,karliatto,1,48,161,21,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...
2,214549887,1185610000000000000,10/19/2019 17:20,9,0,b'RT @s_mario_havel: #Decentruck visiting @LNc...,Karliatto,karliatto,1,48,161,21,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...
3,214549887,1182190000000000000,10/10/2019 7:01,0,1,"b'@M5Stack @M5Stack This looks amazing, what ...",Karliatto,karliatto,1,48,161,21,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...
4,214549887,1181840000000000000,10/9/2019 8:09,2254,0,b'RT @ScottDisick: https://t.co/9tSjFM6zjM has...,Karliatto,karliatto,1,48,161,21,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...

In [9]:
A = tweet['created_at']

In [10]:
len(A)

139912

In [11]:
date = []
time = []
for i in range(0,139912):
    new_date = A[i].split(' ')[0]
    new_time = A[i].split(' ')[1]
    date.append(new_date)
    time.append(new_time)

In [12]:
date

['11/4/2019',
 '10/21/2019',
 '10/19/2019',
 '10/10/2019',
 '10/9/2019',
 '10/5/2019',
 '10/5/2019',
 '10/5/2019',
 '9/3/2019',
 '9/3/2019',
 '8/30/2019',
 '8/1/2019',
 '7/30/2019',
 '6/29/2019',
 '6/27/2019',
 '6/18/2019',
 '6/14/2019',
 '6/13/2019',
 '6/12/2019',
 '4/18/2019',
 '11/23/2018',
 '9/13/2016',
 '3/21/2015',
 '1/31/2015',
 '1/31/2015',
 '1/20/2015',
 '1/17/2015',
 '9/28/2014',
 '8/29/2012',
 '7/24/2012',
 '4/4/2012',
 '4/4/2012',
 '4/4/2012',
 '3/29/2012',
 '3/22/2012',
 '3/22/2012',
 '3/22/2012',
 '3/22/2012',
 '3/22/2012',
 '2/12/2012',
 '2/12/2012',
 '2/12/2012',
 '2/12/2012',
 '2/12/2012',
 '5/6/2011',
 '5/6/2011',
 '5/6/2011',
 '4/24/2011',
 '4/24/2011',
 '4/24/2011',
 '2/1/2011',
 '2/1/2011',
 '10/5/2010',
 '10/5/2010',
 '10/5/2010',
 '10/5/2010',
 '10/5/2010',
 '10/5/2010',
 '8/26/2010',
 '8/26/2010',
 '7/28/2010',
 '7/28/2010',
 '6/2/2010',
 '6/2/2010',
 '6/2/2010',
 '5/6/2010',
 '2/20/2010',
 '2/20/2010',
 '1/21/2010',
 '1/19/2010',
 '1/19/2010',
 '1/19/2010',
 '11/18/2009',
 '11/18/2009',
 '10/27/2009',
 '10/24/2009',
 '10/24/2009',
 '10/20/2009',
 '10/11/2009',
 '10/2/2009',
 '10/2/2009',
 '10/2/2009',
 '10/1/2009',
 '10/1/2009',
 '10/1/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/30/2009',
 '9/28/2009',
 '9/28/2009',
 '9/28/2009',
 '9/28/2009',
 '9/28/2009',
 '9/28/2009',
 '9/28/2009',
 '9/28/2009',
 '9/27/2009',
 '9/27/2009',
 '9/27/2009',
 '9/27/2009',
 '9/26/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/25/2009',
 '9/24/2009',
 '9/24/2009',
 '9/24/2009',
 '9/24/2009',
 '9/24/2009',
 '9/23/2009',
 '9/23/2009',
 '9/23/2009',
 '9/23/2009',
 '9/23/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '9/22/2009',
 '12/6/2011',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/24/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/23/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/22/2013',
 '6/21/2013',
 '6/17/2013',
 '5/31/2013',
 '5/29/2013',
 '6/6/2013',
 '4/26/2013',
 '4/19/2013',
 '4/6/2013',
 '3/25/2013',
 '3/18/2013',
 '3/4/2013',
 '2/24/2013',
 '2/23/2013',
 '2/21/2013',
 '2/15/2013',
 '2/8/2013',
 '2/5/2013',
 '1/31/2013',
 '10/30/2016',
 '11/27/2013',
 '11/27/2013',
 '11/25/2013',
 '10/27/2013',
 '10/27/2013',
 '10/21/2013',
 '1/29/2012',
 '12/28/2011',
 '7/6/2019',
 '6/22/2019',
 '6/22/2019',
 '5/12/2013',
 '5/8/2013',
 '2/21/2013',
 '12/19/2012',
 '11/27/2012',
 '11/17/2012',
 '11/12/2012',
 '11/9/2012',
 '10/25/2012',
 '9/27/2012',
 '1/18/2012',
 '1/7/2012',
 '1/6/2012',
 '5/17/2013',
 '5/5/2013',
 '4/23/2013',
 '4/17/2013',
 '4/30/2013',
 '4/30/2013',
 '7/9/2013',
 '7/9/2013',
 '7/9/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/8/2013',
 '7/7/2013',
 '7/7/2013',
 '7/7/2013',
 '7/7/2013',
 '7/6/2013',
 '7/6/2013',
 '7/6/2013',
 '7/6/2013',
 '7/6/2013',
 '7/6/2013',
 '7/6/2013',
 '7/6/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/5/2013',
 '7/4/2013',
 '7/4/2013',
 '7/4/2013',
 '7/4/2013',
 '7/4/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/3/2013',
 '7/2/2013',
 '7/2/2013',
 '7/2/2013',
 '7/2/2013',
 '7/2/2013',
 '7/2/2013',
 '7/2/2013',
 '6/30/2013',
 '6/29/2013',
 '6/29/2013',
 '6/28/2013',
 '6/28/2013',
 '6/28/2013',
 '6/28/2013',
 '6/28/2013',
 '6/27/2013',
 '6/27/2013',
 '6/27/2013',
 '6/27/2013',
 '6/27/2013',
 '6/27/2013',
 '6/21/2013',
 '6/21/2013',
 '6/21/2013',
 '6/20/2013',
 '6/17/2013',
 '6/17/2013',
 '6/17/2013',
 '6/17/2013',
 '6/10/2013',
 '6/10/2013',
 '6/10/2013',
 '6/10/2013',
 '6/10/2013',
 '6/10/2013',
 '6/8/2013',
 '6/7/2013',
 '6/7/2013',
 '6/6/2013',
 '6/6/2013',
 '6/5/2013',
 '6/5/2013',
 '6/5/2013',
 '6/4/2013',
 '6/4/2013',
 '6/3/2013',
 '6/2/2013',
 '6/2/2013',
 '6/2/2013',
 '5/28/2013',
 '5/28/2013',
 '5/28/2013',
 '5/28/2013',
 '5/27/2013',
 '5/27/2013',
 '5/26/2013',
 '5/26/2013',
 '5/26/2013',
 '5/26/2013',
 '5/26/2013',
 '2/23/2013',
 '2/21/2013',
 '2/20/2013',
 '2/20/2013',
 '2/20/2013',
 '2/18/2013',
 '2/12/2013',
 '1/26/2013',
 '1/13/2013',
 '1/12/2013',
 '1/10/2013',
 '1/10/2013',
 '1/9/2013',
 '1/8/2013',
 '1/5/2013',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '9/5/2012',
 '6/29/2012',
 '5/29/2012',
 '10/30/2014',
 '10/30/2014',
 '10/30/2014',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '6/20/2013',
 '1/8/2013',
 '2/20/2011',
 '8/31/2013',
 '11/12/2012',
 '11/12/2012',
 '7/24/2012',
 '7/14/2012',
 '7/14/2012',
 '7/10/2012',
 '7/10/2012',
 '7/10/2012',
 '7/10/2012',
 '6/24/2012',
 '6/23/2012',
 '6/23/2012',
 '6/15/2012',
 '4/29/2012',
 '3/31/2012',
 '10/7/2011',
 '10/7/2011',
 '10/7/2011',
 '10/1/2011',
 '9/1/2011',
 '8/31/2011',
 '8/23/2011',
 '8/17/2011',
 '7/10/2011',
 '7/10/2011',
 '7/10/2011',
 '7/10/2011',
 '7/7/2011',
 '7/1/2011',
 '6/29/2011',
 '6/26/2011',
 '6/26/2011',
 '6/26/2011',
 '6/23/2011',
 '6/19/2011',
 '6/16/2011',
 '5/25/2011',
 '5/25/2011',
 '4/12/2011',
 '2/10/2011',
 '2/10/2011',
 '2/9/2011',
 '2/9/2011',
 '2/9/2011',
 '2/9/2011',
 '2/8/2011',
 '2/7/2011',
 '2/4/2011',
 '2/3/2011',
 '2/2/2011',
 '2/2/2011',
 '2/2/2011',
 '2/2/2011',
 '2/2/2011',
 '1/28/2011',
 '1/25/2011',
 '1/25/2011',
 '1/23/2011',
 '1/14/2011',
 '1/14/2011',
 '1/14/2011',
 '1/14/2011',
 '1/12/2011',
 '1/6/2011',
 '1/6/2011',
 '1/6/2011',
 '4/19/2013',
 '5/3/2013',
 '5/3/2013',
 '1/8/2013',
 '3/25/2011',
 '3/20/2011',
 '4/20/2016',
 '4/20/2016',
 '4/20/2016',
 '4/20/2016',
 '4/20/2016',
 '4/17/2016',
 '4/9/2016',
 '4/9/2016',
 '4/9/2016',
 '4/3/2016',
 '4/3/2016',
 '4/3/2016',
 '4/3/2016',
 '3/30/2016',
 '3/28/2016',
 '3/28/2016',
 '3/26/2016',
 '3/26/2016',
 '3/26/2016',
 '3/26/2016',
 '3/26/2016',
 '3/26/2016',
 '3/26/2016',
 '3/26/2016',
 '3/23/2016',
 '3/20/2016',
 '3/20/2016',
 '3/20/2016',
 '12/13/2015',
 '11/1/2015',
 '10/31/2015',
 '10/31/2015',
 '10/31/2015',
 '10/31/2015',
 '10/31/2015',
 '10/27/2013',
 '12/18/2012',
 '12/15/2012',
 '6/24/2011',
 '6/24/2011',
 '11/30/2015',
 '2/27/2015',
 '1/25/2015',
 '1/4/2015',
 '12/8/2014',
 '11/24/2014',
 '11/24/2014',
 '11/2/2014',
 '11/1/2014',
 '11/1/2014',
 '11/1/2014',
 '10/8/2014',
 '8/24/2014',
 '8/24/2014',
 '6/11/2014',
 '6/11/2014',
 '5/18/2014',
 '5/12/2014',
 '5/12/2014',
 '4/16/2014',
 '3/11/2014',
 '1/10/2014',
 '1/7/2014',
 '6/13/2013',
 '6/11/2013',
 '4/8/2013',
 '4/6/2013',
 '3/31/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '6/11/2013',
 '3/15/2013',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '12/24/2012',
 '5/17/2013',
 '4/23/2013',
 '7/21/2014',
 '7/19/2014',
 '7/19/2014',
 '4/13/2014',
 '4/6/2014',
 '3/31/2014',
 '3/25/2014',
 '3/11/2014',
 '3/3/2014',
 '3/3/2014',
 '3/2/2014',
 '2/23/2014',
 '2/22/2014',
 '2/9/2014',
 '2/7/2014',
 '2/5/2014',
 '1/28/2014',
 '1/27/2014',
 '1/25/2014',
 '1/18/2014',
 '1/18/2014',
 '1/11/2014',
 '1/10/2014',
 '1/3/2014',
 '1/3/2014',
 '12/29/2013',
 '12/29/2013',
 '12/29/2013',
 '12/28/2013',
 '12/28/2013',
 '12/28/2013',
 '12/27/2013',
 '12/26/2013',
 '12/19/2013',
 '12/12/2013',
 '12/9/2013',
 '12/3/2013',
 '12/2/2013',
 '11/25/2013',
 '11/25/2013',
 '11/22/2013',
 '11/22/2013',
 '11/19/2013',
 '11/12/2013',
 '11/10/2013',
 '11/8/2013',
 '11/8/2013',
 '11/6/2013',
 '11/5/2013',
 '11/4/2013',
 '10/30/2013',
 '10/29/2013',
 '10/27/2013',
 '10/26/2013',
 '10/25/2013',
 '10/21/2013',
 '10/15/2013',
 '10/14/2013',
 '10/12/2013',
 '10/12/2013',
 '10/12/2013',
 '10/11/2013',
 '10/8/2013',
 '9/30/2013',
 '9/30/2013',
 '9/25/2013',
 '9/21/2013',
 '7/27/2013',
 '7/26/2013',
 '7/26/2013',
 '7/26/2013',
 '7/26/2013',
 '7/26/2013',
 '7/26/2013',
 '7/22/2013',
 '7/6/2013',
 '7/5/2013',
 '7/5/2013',
 '7/2/2013',
 '6/28/2013',
 '6/27/2013',
 '6/25/2013',
 '6/24/2013',
 '6/13/2013',
 '6/11/2013',
 '6/5/2013',
 '6/4/2013',
 '6/2/2013',
 '5/28/2013',
 '5/25/2013',
 '5/21/2013',
 '5/17/2013',
 '5/14/2013',
 '5/10/2013',
 '5/7/2013',
 '5/7/2013',
 '5/7/2013',
 '5/6/2013',
 '5/4/2013',
 '5/4/2013',
 '4/29/2013',
 '4/23/2013',
 '4/16/2013',
 '4/15/2013',
 '4/12/2013',
 '4/11/2013',
 '4/9/2013',
 '4/8/2013',
 '4/4/2013',
 '4/3/2013',
 '4/2/2013',
 '4/1/2013',
 '3/30/2013',
 '3/30/2013',
 '3/28/2013',
 '3/28/2013',
 '3/25/2013',
 '3/21/2013',
 '3/20/2013',
 '3/19/2013',
 '3/15/2013',
 '3/13/2013',
 '3/13/2013',
 '3/12/2013',
 '3/11/2013',
 '3/10/2013',
 '3/9/2013',
 '3/8/2013',
 '3/8/2013',
 '3/8/2013',
 '3/7/2013',
 '3/6/2013',
 '3/5/2013',
 '3/5/2013',
 '3/4/2013',
 '3/3/2013',
 '3/2/2013',
 '3/2/2013',
 '3/1/2013',
 '3/1/2013',
 '3/1/2013',
 '2/28/2013',
 '2/28/2013',
 '2/28/2013',
 '2/28/2013',
 '2/27/2013',
 '2/27/2013',
 '2/26/2013',
 '2/25/2013',
 '2/25/2013',
 '2/25/2013',
 '2/25/2013',
 '2/23/2013',
 '2/23/2013',
 '2/23/2013',
 '2/23/2013',
 '2/22/2013',
 '2/21/2013',
 '2/20/2013',
 '2/19/2013',
 '2/19/2013',
 '2/19/2013',
 '2/18/2013',
 '2/18/2013',
 '2/18/2013',
 '2/18/2013',
 '2/18/2013',
 '2/18/2013',
 '2/17/2013',
 '2/17/2013',
 '2/17/2013',
 '2/17/2013',
 '2/17/2013',
 '2/17/2013',
 '2/16/2013',
 '2/16/2013',
 '2/15/2013',
 '2/15/2013',
 '2/15/2013',
 '2/15/2013',
 '2/13/2013',
 '2/13/2013',
 '2/13/2013',
 '2/12/2013',
 '2/11/2013',
 '2/11/2013',
 '2/11/2013',
 '2/11/2013',
 '2/11/2013',
 '2/10/2013',
 '2/10/2013',
 '2/10/2013',
 '2/9/2013',
 '2/9/2013',
 '2/9/2013',
 '2/9/2013',
 '2/9/2013',
 '2/8/2013',
 '2/8/2013',
 '2/8/2013',
 '2/8/2013',
 '2/8/2013',
 ...]

In [15]:
pf = pd.DataFrame({'created_at':A,
                   'date':date,
                   'time':time})

In [16]:
pf

              created_at        date   time
0         11/4/2019 9:27   11/4/2019   9:27
1       10/21/2019 13:27  10/21/2019  13:27
2       10/19/2019 17:20  10/19/2019  17:20
3        10/10/2019 7:01  10/10/2019   7:01
4         10/9/2019 8:09   10/9/2019   8:09
...                  ...         ...    ...
139907    1/18/2018 8:00   1/18/2018   8:00
139908    1/18/2018 7:56   1/18/2018   7:56
139909    1/18/2018 6:39   1/18/2018   6:39
139910    1/18/2018 6:32   1/18/2018   6:32
139911  10/30/2012 20:00  10/30/2012  20:00

[139912 rows x 3 columns]

In [17]:
data = pd.merge(tweet, pf,on = 'created_at', how = 'inner') 
data

,id,tweet_id,created_at,retweet_count,favorite_count,text,name,screen_name,bot_type,#of_followers,...,url,lang,time_zone,location,default_profile,default_profile_image,geo_enabled,profile_image_url,date,time
0,214549887,1191290000000000000,11/4/2019 9:27,0,0,b'@walletofsatoshi @ChipiChipiBmbn @fabthefoxx...,Karliatto,karliatto,1,48,...,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...,11/4/2019,9:27
1,214549887,1186270000000000000,10/21/2019 13:27,4,18,b'Still digesting the experience at @LNconf #T...,Karliatto,karliatto,1,48,...,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...,10/21/2019,13:27
2,214549887,1185610000000000000,10/19/2019 17:20,9,0,b'RT @s_mario_havel: #Decentruck visiting @LNc...,Karliatto,karliatto,1,48,...,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...,10/19/2019,17:20
3,214549887,1182190000000000000,10/10/2019 7:01,0,1,"b'@M5Stack @M5Stack This looks amazing, what ...",Karliatto,karliatto,1,48,...,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...,10/10/2019,7:01
4,214549887,1181840000000000000,10/9/2019 8:09,2254,0,b'RT @ScottDisick: https://t.co/9tSjFM6zjM has...,Karliatto,karliatto,1,48,...,https://t.co/XsIz44KmAp,None,None,Prague,False,False,False,http://pbs.twimg.com/profile_images/113598448...,10/9/2019,8:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332057,915389299,953900000000000000,1/18/2018 8:00,1,0,b'RT @BigTolver22: My next dog better bark lik...,Zakso_fonista,zakso_fonista,2,12,...,None,None,None,"Valdivia, Chile",False,True,False,http://abs.twimg.com/sticky/default_profile_i...,1/18/2018,8:00
332058,915389299,953899000000000000,1/18/2018 7:56,2,0,b'RT @xprezz: @TopRight_Nordic Vilken fantas...,Zakso_fonista,zakso_fonista,2,12,...,None,None,None,"Valdivia, Chile",False,True,False,http://abs.twimg.com/sticky/default_profile_i...,1/18/2018,7:56
332059,915389299,953880000000000000,1/18/2018 6:39,4,0,b'RT @szybki_yt: Check out my recent video!htt...,Zakso_fonista,zakso_fonista,2,12,...,None,None,None,"Valdivia, Chile",False,True,False,http://abs.twimg.com/sticky/default_profile_i...,1/18/2018,6:39
332060,915389299,953878000000000000,1/18/2018 6:32,1,0,b'RT @gashadokkuro: Futakuchi-onna https://t.c...,Zakso_fonista,zakso_fonista,2,12,...,None,None,None,"Valdivia, Chile",False,True,False,http://abs.twimg.com/sticky/default_profile_i...,1/18/2018,6:32
332061,915389299,263370000000000000,10/30/2012 20:00,0,1,b'la pamela dias es aprobechadora y SACA PICA',Zakso_fonista,zakso_fonista,2,12,...,None,None,None,"Valdivia, Chile",False,True,False,http://abs.twimg.com/sticky/default_profile_i...,10/30/2012,20:00

In [18]:
D1 = data[['id','tweet_id','date','time','text']]
D1

,id,tweet_id,date,time,text
0,214549887,1191290000000000000,11/4/2019,9:27,b'@walletofsatoshi @ChipiChipiBmbn @fabthefoxx...
1,214549887,1186270000000000000,10/21/2019,13:27,b'Still digesting the experience at @LNconf #T...
2,214549887,1185610000000000000,10/19/2019,17:20,b'RT @s_mario_havel: #Decentruck visiting @LNc...
3,214549887,1182190000000000000,10/10/2019,7:01,"b'@M5Stack @M5Stack This looks amazing, what ..."
4,214549887,1181840000000000000,10/9/2019,8:09,b'RT @ScottDisick: https://t.co/9tSjFM6zjM has...
...,...,...,...,...,...
332057,915389299,953900000000000000,1/18/2018,8:00,b'RT @BigTolver22: My next dog better bark lik...
332058,915389299,953899000000000000,1/18/2018,7:56,b'RT @xprezz: @TopRight_Nordic Vilken fantas...
332059,915389299,953880000000000000,1/18/2018,6:39,b'RT @szybki_yt: Check out my recent video!htt...
332060,915389299,953878000000000000,1/18/2018,6:32,b'RT @gashadokkuro: Futakuchi-onna https://t.c...
332061,915389299,263370000000000000,10/30/2012,20:00,b'la pamela dias es aprobechadora y SACA PICA'

In [19]:
data.groupby('id').date.value_counts()

id          date
7732472     4/8/2014     18
            4/2/2014     16
            2/9/2014      9
            1/13/2015     8
            1/27/2016     7
                         ..
4778298479  3/3/2018     13
            1/18/2016     2
            1/19/2016     1
            1/28/2016     1
            3/9/2016      1
Name: date, Length: 44367, dtype: int64

In [84]:
tweet_id_count = data.groupby('id').tweet_id.value_counts()
K=pd.DataFrame(tweet_id_count)

In [63]:
user_id = set(tweet['id'])
user_id

{7732472,
 14938781,
 15947185,
 17640121,
 21479515,
 21479634,
 21479977,
 21480027,
 21484370,
 21629735,
 21696097,
 21723832,
 21967510,
 22030724,
 22256645,
 22293089,
 22578323,
 22597402,
 22663627,
 22728442,
 22930291,
 23140706,
 23162965,
 23222296,
 23225490,
 23257723,
 23258239,
 23264565,
 23504921,
 24213618,
 24222336,
 24224607,
 24315455,
 24317752,
 24321441,
 24385142,
 24387166,
 24601131,
 24602801,
 25006080,
 25060110,
 25449898,
 25775049,
 27159435,
 28587018,
 30428221,
 30969945,
 31228692,
 33633835,
 33869550,
 33877660,
 34589722,
 35008954,
 35959749,
 36477176,
 37302537,
 37369373,
 37384589,
 37935992,
 37983502,
 38039576,
 38054032,
 38054164,
 38081689,
 38106309,
 38106485,
 38106903,
 38107317,
 38164107,
 38191818,
 38211602,
 38212146,
 38962259,
 39156016,
 40010436,
 41620770,
 41638585,
 41638698,
 41655099,
 41670875,
 41678763,
 41686590,
 41982078,
 42157433,
 42157628,
 43258850,
 43259836,
 43747581,
 44191269,
 45804432,
 47678112,
 47722321,
 48638750,
 48712444,
 49270232,
 49588893,
 49669394,
 49772550,
 49853823,
 49949709,
 50346336,
 50552240,
 51905951,
 51949191,
 52039977,
 52615792,
 53714790,
 53780726,
 53784356,
 53948371,
 54234822,
 54244742,
 54353595,
 54891461,
 55221873,
 55243788,
 55256821,
 55275603,
 55396146,
 55412037,
 58384179,
 58624454,
 59434448,
 59904140,
 60257479,
 60375971,
 60430191,
 62204600,
 62730539,
 63065682,
 63312941,
 63417814,
 63579810,
 63737626,
 64148519,
 64169835,
 64297402,
 64636395,
 64725115,
 64987143,
 65257967,
 65332295,
 66618364,
 66807259,
 67004702,
 67242405,
 67404263,
 67537846,
 67595009,
 67604511,
 67604772,
 67946273,
 68203632,
 68246597,
 68332605,
 68918886,
 69201180,
 69202294,
 69218933,
 69280475,
 69412978,
 69492703,
 69502707,
 69509049,
 70038696,
 71467598,
 71564424,
 71635706,
 71722242,
 71776798,
 71793700,
 71826144,
 71940079,
 71943510,
 71966331,
 72033272,
 72041194,
 72042541,
 72059138,
 72068550,
 72076822,
 72186699,
 72207735,
 72208069,
 72209365,
 72211081,
 72373568,
 72432504,
 72852291,
 72979450,
 73049791,
 73246645,
 73851157,
 73851368,
 74120658,
 74389659,
 74630038,
 74637832,
 74638959,
 74995296,
 75710563,
 75727230,
 75863742,
 75999733,
 76000096,
 76361849,
 76530984,
 77161645,
 77243796,
 77413855,
 77727490,
 78423507,
 78466461,
 79361616,
 79362510,
 79443295,
 79860976,
 79966861,
 80194139,
 80345479,
 80479674,
 82100136,
 82122078,
 83210368,
 84114859,
 84325988,
 84602929,
 85126240,
 85254758,
 86517226,
 87752806,
 88004842,
 88563527,
 91162581,
 91350980,
 91781300,
 92041890,
 93083959,
 94528740,
 95690748,
 96668347,
 96917059,
 97275343,
 98888058,
 99323986,
 99545852,
 101330311,
 101330413,
 101615403,
 101647448,
 102508730,
 102514432,
 103020806,
 103614496,
 103688844,
 103919687,
 104256888,
 104394959,
 104520384,
 104896954,
 104897023,
 104991578,
 105748476,
 105790281,
 106301592,
 106378113,
 106394146,
 106522802,
 107436496,
 107549781,
 107727712,
 107914508,
 109066883,
 109075883,
 109633855,
 112131340,
 112429918,
 112540516,
 112544426,
 114079307,
 114488344,
 116016837,
 119227710,
 121309790,
 122511648,
 123599990,
 124419079,
 125514462,
 128620164,
 129549447,
 130061775,
 132278621,
 134332869,
 134678238,
 137515361,
 137959629,
 138667565,
 140176665,
 147852405,
 147954455,
 148896431,
 150861478,
 152259498,
 152846674,
 154237500,
 154856763,
 156922624,
 157882115,
 157882740,
 157884271,
 157899229,
 157899996,
 158541730,
 162035733,
 165778169,
 165790334,
 168218491,
 168872531,
 169147207,
 169474438,
 170144297,
 170241204,
 172164229,
 173215914,
 176096243,
 176506844,
 177671726,
 179295032,
 179562837,
 182390315,
 184667668,
 185933483,
 189015964,
 190796770,
 193818184,
 194777903,
 194780405,
 195005434,
 195006541,
 195017418,
 195018333,
 195019019,
 195049424,
 195625268,
 198243810,
 198277538,
 201190422,
 201425184,
 210428729,
 212779829,
 212882298,
 214549887,
 214632102,
 215154980,
 215663794,
 215693377,
 217992483,
 220097040,
 224567425,
 227650216,
 228720947,
 229906054,
 233884874,
 234587511,
 237036122,
 237178034,
 237860975,
 238531661,
 239910996,
 240422007,
 241041165,
 241206543,
 241228977,
 241243279,
 241312583,
 241915215,
 242206951,
 242534704,
 243556904,
 243707462,
 244202085,
 244568143,
 249011468,
 250970687,
 253111142,
 253239439,
 254394005,
 254618989,
 254839933,
 254976820,
 258069307,
 261915122,
 263549739,
 265551997,
 266064479,
 267092571,
 267781978,
 269201871,
 270442712,
 270494010,
 275881452,
 278082770,
 279388955,
 291191096,
 293830909,
 294687282,
 295394982,
 297021045,
 297548417,
 297613967,
 304196805,
 306207069,
 306479404,
 307819895,
 309434421,
 310462159,
 313626619,
 314162343,
 314201545,
 314265702,
 317248347,
 317953097,
 319802566,
 325789799,
 326241359,
 327747371,
 327748532,
 330531182,
 331801034,
 331801886,
 331809299,
 334163536,
 334747962,
 334748859,
 334754360,
 334825381,
 334826952,
 335192481,
 335405859,
 335409261,
 336051161,
 336713356,
 337161218,
 337653685,
 339021400,
 346747046,
 346790259,
 347506040,
 347579782,
 347587058,
 347595019,
 349979518,
 351889016,
 355303911,
 355821619,
 355843642,
 355993172,
 357088003,
 357110189,
 358424054,
 360201053,
 360743981,
 360747829,
 365334598,
 370384848,
 370960192,
 373612487,
 377408959,
 377994769,
 382916532,
 384501016,
 390471074,
 391017238,
 393352485,
 395458764,
 398813548,
 400069220,
 401190123,
 401287742,
 407185445,
 407371142,
 411288201,
 413650968,
 419862060,
 420658286,
 422415442,
 422510662,
 430175527,
 430928749,
 433495525,
 434727810,
 434775697,
 434795107,
 435591257,
 448310199,
 451920644,
 455075718,
 456934703,
 456939896,
 457013718,
 458941316,
 461290098,
 465325633,
 465393290,
 465405613,
 465418896,
 465431259,
 466109264,
 466139143,
 466161043,
 466189857,
 466221249,
 466241419,
 466267904,
 466272878,
 466289763,
 466293888,
 466295605,
 466309651,
 466310732,
 466314172,
 466365951,
 466366851,
 466372053,
 466379768,
 466386773,
 466387081,
 466395857,
 466409574,
 466415815,
 466485845,
 466602487,
 467095185,
 467105761,
 467109176,
 467110763,
 467132777,
 467136996,
 467153239,
 467180613,
 468059646,
 468099552,
 468126635,
 468129657,
 468155641,
 468691190,
 469178446,
 470080932,
 475035176,
 479896389,
 481767405,
 486647349,
 509680266,
 512084670,
 514736144,
 516315537,
 520998731,
 522334559,
 522574094,
 531130708,
 531134291,
 531134893,
 531135197,
 531137422,
 531138997,
 531141808,
 531141814,
 531144512,
 531146284,
 531148316,
 531148975,
 531151339,
 531152071,
 531153134,
 531154412,
 531154466,
 531155971,
 531156196,
 531157556,
 531158939,
 531160150,
 531165847,
 531166864,
 531167072,
 531170783,
 531170807,
 531217335,
 531218934,
 531219372,
 531230127,
 531237552,
 531240150,
 531250998,
 535781152,
 538453053,
 539052577,
 539157095,
 542163896,
 542412215,
 545647644,
 545708233,
 548300100,
 549394334,
 559842571,
 569193926,
 569994470,
 570726762,
 576226470,
 576917802,
 580925947,
 585411607,
 585624973,
 585856581,
 585956153,
 586123464,
 605294402,
 613617309,
 616211479,
 617486653,
 619027215,
 621555892,
 626820204,
 703914774,
 707991344,
 711479551,
 711494346,
 711547033,
 721305198,
 766190970,
 773903504,
 817101949,
 845770021,
 869150966,
 909766628,
 915389299,
 926780918,
 949652516,
 956473088,
 962735887,
 968615329,
 969672378,
 982414274,
 1013031680,
 1013213588,
 1021573561,
 1103129532,
 1103573989,
 1119638359,
 1124807293,
 1127237954,
 1129940900,
 1169254332,
 1174403390,
 1174413920,
 1174804556,
 1190158771,
 1207835467,
 1208229229,
 1273211215,
 1303391600,
 1367040230,
 1369249873,
 1369408290,
 1369480706,
 1370348599,
 1372026204,
 1372882284,
 1373641104,
 1380853662,
 1382419244,
 1386549638,
 1387393236,
 1388028872,
 1388819528,
 1391622127,
 1424964542,
 1517148602,
 1518824575,
 1532898176,
 1536537319,
 1568510904,
 1580244270,
 1699325190,
 1703777425,
 1857062660,
 1858638313,
 1870952172,
 1907435238,
 2183757256,
 2212593386,
 2231823601,
 2234906166,
 2260177964,
 2262529256,
 2263955958,
 2264854836,
 2266193642,
 2268586645,
 2268606518,
 2268625764,
 2274254095,
 2277224702,
 2281419193,
 2281719673,
 2348957142,
 2350056632,
 2350477716,
 2350916618,
 2350961034,
 2351219077,
 2351559656,
 2351824118,
 2351935423,
 2352008196,
 2352067280,
 2352110226,
 2352158130,
 2352159972,
 2352187580,
 2352207456,
 2352247068,
 2352702752,
 2352739142,
 2352828182,
 2352831228,
 2352846920,
 2353047476,
 2353260758,
 2353351447,
 2353400918,
 2353562042,
 2353568059,
 2353578306,
 2353624196,
 2353718966,
 2354063478,
 2354069323,
 2354084184,
 2354116309,
 2354194003,
 2354254531,
 2354667518,
 2354826618,
 2354846455,
 2355003306,
 2355068754,
 2355678560,
 2355838308,
 2355860940,
 2355930697,
 2356086913,
 2356197007,
 2356911834,
 2356992192,
 2357047370,
 2357051431,
 2357317176,
 2357427223,
 2357496132,
 2357889667,
 2357907529,
 2358098166,
 2358208177,
 2358250249,
 2358663804,
 2358710996,
 2359711226,
 2360091846,
 2360182716,
 2360206722,
 2360228768,
 2360251669,
 2360482604,
 2360648678,
 2361319741,
 2361352586,
 2361587412,
 2361675468,
 2361700004,
 2361704293,
 2362227691,
 2362315692,
 2362425720,
 2362544011,
 2362599654,
 2362667418,
 2363203543,
 2363279784,
 2363464135,
 2363606850,
 2363643973,
 2364065282,
 2364236432,
 2364278676,
 2366113250,
 2366546125,
 2366559954,
 2366598108,
 2368471386,
 2368720850,
 2370390223,
 2370729744,
 2370793416,
 2370874855,
 2371056121,
 2371108268,
 2372253000,
 2372328596,
 2372355884,
 2372365974,
 2372957832,
 2372968790,
 2374328761,
 2374446264,
 2374553130,
 2375209765,
 2375595570,
 2376970520,
 2377108531,
 2377935157,
 2378476622,
 2378812603,
 2379702133,
 2380383847,
 2380732760,
 2380735502,
 2380870878,
 2380880329,
 2381212399,
 2381447276,
 2382299202,
 2382480786,
 2382818402,
 2383162592,
 2383403694,
 2383725247,
 2384187024,
 2384243040,
 2384614712,
 2384657844,
 2384784373,
 2384832716,
 2385017492,
 2386012454,
 2386538774,
 2391867347,
 2392882105,
 2448331436,
 2495663488,
 2558753784,
 2577279787,
 2579207780,
 2579211932,
 2580232604,
 2580268597,
 2580592724,
 2581844526,
 2583735798,
 2615946960,
 2645582425,
 2645788448,
 2647655401,
 2677641872,
 2677896769,
 2700434262,
 2723773225,
 2732397842,
 2732446718,
 2766113040,
 2766137106,
 2766181627,
 2785373829,
 2786138968,
 2786184251,
 2786192464,
 2786943825,
 2786980305,
 2787014584,
 2787053566,
 2787057239,
 2790626649,
 2791704203,
 2813786985,
 2814135472,
 2814893105,
 2815531324,
 2815546623,
 2815655381,
 2815669702,
 2881189474,
 2882469599,
 2888024378,
 2910051577,
 2935209041,
 2942470996,
 2966279225,
 2967468803,
 2972849692,
 2974415139,
 2998463923,
 3032781021,
 3042874674,
 3055225969,
 3153362979,
 3157341339,
 3165893411,
 3167942682,
 3167950890,
 3167962440,
 3167964494,
 3167971386,
 3167992778,
 3168018530,
 3168022627,
 3168028789,
 3168029725,
 3168040651,
 3168041323,
 3168042265,
 3168043903,
 3168044893,
 3168047107,
 3193988145,
 3227904608,
 3229520827,
 3229551091,
 3231014982,
 3231291522,
 3231315638,
 3231842864,
 3231874357,
 3231879564,
 3231976172,
 3232215462,
 3234328321,
 3235009453,
 3235105898,
 3238777032,
 3302446791,
 3302525926,
 3302530024,
 3303491711,
 3305460917,
 3307816547,
 3308945967,
 4299178814,
 4331279781,
 4778298479}

                                tweet_id
id         tweet_id
7732472    451376000000000000         16
           453571000000000000         16
           432555000000000000          9
           471334000000000000          4
           471686000000000000          4
           474275000000000000          4
           782246000000000000          4
           453998000000000000          2
           454614000000000000          2
           455946000000000000          2
           456338000000000000          2
           508941000000000000          2
           692143000000000000          2
           378141000000000000          1
           378178000000000000          1
           378198000000000000          1
           378261000000000000          1
           378459000000000000          1
           378480000000000000          1
           378737000000000000          1
           378775000000000000          1
           378979000000000000          1
           379114000000000000          1
           379209000000000000          1
           379539000000000000          1
           382160000000000000          1
           387600000000000000          1
           397747000000000000          1
           400303000000000000          1
           400549000000000000          1
...                                  ...
4331279781 1072400000000000000         1
           1072590000000000000         1
           1072770000000000000         1
           1072950000000000000         1
           1073500000000000000         1
           1074220000000000000         1
           1199620000000000000         1
4778298479 972519000000000000          5
           972520000000000000          5
           969797000000000000          4
           972521000000000000          3
           969808000000000000          2
           972529000000000000          2
           972532000000000000          2
           689076000000000000          1
           689118000000000000          1
           689509000000000000          1
           692819000000000000          1
           707673000000000000          1
           969798000000000000          1
           969799000000000000          1
           969802000000000000          1
           969804000000000000          1
           969806000000000000          1
           969807000000000000          1
           969810000000000000          1
           972530000000000000          1
           972533000000000000          1
           972538000000000000          1
           972546000000000000          1

[120640 rows x 1 columns]